// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRLEMKheZyN8l3Pc6kd-A9jNWPSNhBFdA',
    appId: '1:878198376092:web:a38456bb7cee5aa6b90f59',
    messagingSenderId: '878198376092',
    projectId: 'test-auth-eaf78',
    authDomain: 'test-auth-eaf78.firebaseapp.com',
    storageBucket: 'test-auth-eaf78.appspot.com',
    measurementId: 'G-P20NH5T3CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnhoiHFaCbhXZvSfuJV-cmgp9KCb8p4yQ',
    appId: '1:878198376092:android:9211068e3173d10bb90f59',
    messagingSenderId: '878198376092',
    projectId: 'test-auth-eaf78',
    storageBucket: 'test-auth-eaf78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-OSOyKRG16m8SMHU_qkobSRG9S48ZrQ',
    appId: '1:878198376092:ios:5aff9e32a0cd7b83b90f59',
    messagingSenderId: '878198376092',
    projectId: 'test-auth-eaf78',
    storageBucket: 'test-auth-eaf78.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY-OSOyKRG16m8SMHU_qkobSRG9S48ZrQ',
    appId: '1:878198376092:ios:3862c162526c974eb90f59',
    messagingSenderId: '878198376092',
    projectId: 'test-auth-eaf78',
    storageBucket: 'test-auth-eaf78.appspot.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
