// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu9vtj5QjYMYmWAohnum4ea7_mGRE0-pk',
    appId: '1:1000594069805:web:06d963e849359d5ff19ba4',
    messagingSenderId: '1000594069805',
    projectId: 'eureka-44973',
    authDomain: 'eureka-44973.firebaseapp.com',
    databaseURL: 'https://eureka-44973-default-rtdb.firebaseio.com',
    storageBucket: 'eureka-44973.appspot.com',
    measurementId: 'G-DQHE1KSTZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtU4qWeKSqZ4QMO1_BV1faJlWBTWnqc4w',
    appId: '1:1000594069805:android:80052c90b1ec8decf19ba4',
    messagingSenderId: '1000594069805',
    projectId: 'eureka-44973',
    databaseURL: 'https://eureka-44973-default-rtdb.firebaseio.com',
    storageBucket: 'eureka-44973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwIJtpnEXLehgSxRxSnVMLv0YhgO7Uimk',
    appId: '1:1000594069805:ios:a433a59703cd0ac7f19ba4',
    messagingSenderId: '1000594069805',
    projectId: 'eureka-44973',
    databaseURL: 'https://eureka-44973-default-rtdb.firebaseio.com',
    storageBucket: 'eureka-44973.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwIJtpnEXLehgSxRxSnVMLv0YhgO7Uimk',
    appId: '1:1000594069805:ios:1533c92f474d3bfef19ba4',
    messagingSenderId: '1000594069805',
    projectId: 'eureka-44973',
    databaseURL: 'https://eureka-44973-default-rtdb.firebaseio.com',
    storageBucket: 'eureka-44973.appspot.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
